### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by KingMarth** [leonard-IMBERT/StarlightMap#17]
It's good practice to put a clear software license on repositories. Github makes it pretty easy: https://help.github.com/en/articles/adding-a-license-to-a-repository

I recommend the Apache 2 or MIT licenses,

**Comment by leonard-IMBERT** [comment]
I've pushed the LICENSE file. I've chosen MIT because it's simple and make this code easy to use by anybody. Thanks for the notice by the way ;)
